name: EPG_personal

on:
  schedule:
    - cron: '45 11 * * * ' # Ejecutar a las 11:45 AM
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

    - name: Dar permisos de ejecución al script
      run: |
        chmod +x .github/workflows/EPG_script.sh

    - name: Ejecutar script
      run: .github/workflows/EPG_script.sh

      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
