name: EPG_personal

on:
  schedule:
    - cron: '45 11 * * * ' # Ejecutar a las 11:45 AM
  workflow_dispatch: # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Dar permisos de ejecución al script
      run: |
        chmod +x .github/workflows/EPG_script.sh

    - name: Ejecutar script
      run: .github/workflows/EPG_script.sh

    - name: Configurar identidad de Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        
    - name: Subir archivos
      run: |
        git add .
        git commit -m "Crear EPG_personal.xml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
